version: '3'
services:
  behave:
    build: .
    image: behave-selenium
    container_name: behave-selenium
    environment: 
      - BEHAVE_RUN_LOCAL=true
    volumes: 
      - .:/behave
    networks: 
      static-network:
        ipv4_address: 172.23.0.2
networks: 
  static-network:
    ipam:
      config:
        - subnet: 172.23.0.0/16